### ISSUE TITLE
[GWS 2] Reloading all the time 

### ISSUE THREAD

**Issue by AdroDG** [wwwebman/gulp-webpack-starter#4]
Hello, 
Thank you for sharing...
I have discovered that when modifying js code, the page is loading over and over and never stops.
I have seen that thanks to the browsersync notification and dev tools that keeps on blinking all the time.
Any clue ?

**Comment by wwwebman** [comment]
@AdroDG Hi! Does this bug occur when you working with some proxy (e.g. wordpress dev)?

**Comment by wwwebman** [comment]
related to #3

**Comment by AdroDG** [comment]
I think it is somehow related to previous issueyou mentioned.
I have not configured any proxy to answer your question.

In addition to that, I think something like 
		webpackConfig.entry.app.unshift('webpack/hot/dev-server')
is missing webpackConfig.js

I have experimented a little bit around the solution you propose, and do not have perpetual reloading now, but now the hot reloading system do not update code... :(

**Comment by wwwebman** [comment]
@AdroDG  I have found the reason of  'Reloading all the time' in case of proxy...
more about - https://github.com/wwwebman/gulp-webpack-starter/issues/3

I'am really surprised, because if I understand correctly, you just pulled the Repo > `yarn install` > `yarn dev` then you started edit dev\js\* and page start reload infinitely, right?

In fact, i can't reproduce this bug. Could you send some screens and info about node version, OS, browser and so on?

**Comment by wwwebman** [comment]
if you still need help, let's continue on chat - https://gitter.im/gulp-webpack-starter/Lobby
