### ISSUE TITLE
Gulp-Webpack-Starter not for Gulp 4?

### ISSUE THREAD

**Issue by vsevolod-kue** [wwwebman/gulp-webpack-starter#77]
After installing the node modules and run the command "npm run start" the script exists with an error 

assert.js:385
    throw err;
    ^
The setup is the same that is in this repository.

**Comment by wwwebman** [comment]
@vsevolod-kue hi,
1. No, it v2.x uses Gulp 3. Welcome to contribution.
2. I am surprised why you don't follow the issue template?  Sorry, but I can only guess the OS and node.js, npm versions you use. Send me a link to the repo where I can take a look. Otherwise, this info is not enough to reproduce.

**Comment by vsevolod-kue** [comment]
@wwwebman, sorry my bad.

I use the current version of your code.

When I run "npm run start" in the root directory, I get now the following message 

> fs.js:35
} = primordials;
> ReferenceError: primordials is not defined

My system is macOS Catalina, nodeversion v12.16.3 and the npm version is 6.14.4.

Do you need more? I will use your code for a wordpress theme.

**Comment by wwwebman** [comment]
@vsevolod-kue,  I see the issue now. The reason is https://github.com/gulpjs/gulp/issues/2324.
The simple solution that comes to my mind is downgrading of node.js to version 10.16.0. Otherwise,  you can wait until I refactor this(can take a while) or contribute to this improvement.
